server:
  port: 8081
spring:
  application:
    name: ddd-application
  ## Spring datasource config
  datasource:
#    driver-class-name: ${JDBC_DRIVER:org.h2.Driver}
    url: ${JDBC_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${JDBC_USERNAME:}
    password: ${JDBC_PASSWORD:}
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true